/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package viewsv;

public class LichSuGiaoDich extends java.awt.Dialog {

    /**
     * Creates new form LichSuGiaoDich
     */
    private SinhVienMain sinhVienMain;
    
    public LichSuGiaoDich(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        sinhVienMain = (SinhVienMain) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLichSuGiaoDich = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tableLichSuGiaoDich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Tên giao dịch", "Ngày giờ", "Số tiền", "Trang thái"
            }
        ));
        tableLichSuGiaoDich.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tableLichSuGiaoDichHierarchyChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tableLichSuGiaoDich);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Lịch sử giao dịch");
        jLabel2.setToolTipText("");
        add(jLabel2, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tableLichSuGiaoDichHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tableLichSuGiaoDichHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tableLichSuGiaoDichHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LichSuGiaoDich dialog = new LichSuGiaoDich(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLichSuGiaoDich;
    // End of variables declaration//GEN-END:variables
}
